# custom manager
[mgr]
show_hidden  = false
show_border  = false
show_symlink = true
title_format = ""
ratio        = [1, 2, 5]

# custom preview
[preview]
wrap            = "no"
tab_size        = 2
max_width       = 5000
max_height      = 5000
cache_dir       = ""
image_delay     = 30
image_filter    = "nearest"
image_quality   = 70
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

# custom action
[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix", desc = "Open with vim" },
]
play = [
	{ run = 'bash "$@"', for = "unix", orphan = true, desc = "Exec bash script" },
]
open = [
	{ run = 'open "$@"', for = "unix", desc = "Open" },
]

[open]
prepend_rules = [
	{ name = "*.json", use = "edit" },
	{ name = "*.ts", use = "edit" },
	{ name = "*.js", use = "edit" },
	{ name = "*.yml", use = "edit" },
	{ name = "*.yaml", use = "edit" },
	{ name = "*.ry", use = "edit" },
	{ name = "*.sh", use = [ "edit", "play" ] },
	{ name = "*.md", use = "edit" },
	{ name = "*.html", use = "edit" },
	{ name = "*.log", use = "edit" },
	{ name = "*.lock", use = "edit" },
	{ name = "*.toml", use = "edit" },
	{ name = "*.pem", use = "edit" },
	{ name = "*", use = "open" },
]

# fetch plugin
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
