# custom manager
[mgr]
show_hidden  = true
show_border  = false
show_symlink = true
title_format = ""
ratio        = [1, 2, 5]

# custom preview
[preview]
wrap            = "no"
tab_size        = 2
max_width       = 5000
max_height      = 5000
cache_dir       = ""
image_delay     = 30
image_filter    = "nearest"
image_quality   = 70
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

# custom action
[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix", desc = "Open with vim" },
]
play = [
	{ run = 'bash "$@"', for = "unix", orphan = true, desc = "Exec bash script" },
]
open = [
	{ run = 'open "$@"', for = "unix", desc = "Open" },
]

[open]
prepend_rules = [
	{ url = "*.json", use = "edit" },
	{ url = "*.ts", use = "edit" },
	{ url = "*.js", use = "edit" },
	{ url = "*.cs", use = "edit" },
	{ url = "*.yml", use = "edit" },
	{ url = "*.yaml", use = "edit" },
	{ url = "*.ry", use = "edit" },
	{ url = "*.sh", use = [ "edit", "play" ] },
	{ url = "*.md", use = "edit" },
	{ url = "*.html", use = "edit" },
	{ url = "*.log", use = "edit" },
	{ url = "*.lock", use = "edit" },
	{ url = "*.toml", use = "edit" },
	{ url = "*.pem", use = "edit" },
	{ url = "*", use = "open" },
]

[plugin]
prepend_fetchers = [
  { group = "git", url = "*", run = "git" },
  { group = "git", url = "*/", run = "git" }
]
